language: scala
scala:
- "2.13"
dist: xenial

script:
  - ./mill --disable-ticker _._.test
#  - mill --disable-ticker jose.json._.test

deploy:
  skip_cleanup: true
  provider: script
  script: bash -xeu ci/deploy.sh
  on:
    tags: true
